#ifndef SHARE_X_H
#define SHARE_X_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

/*
 * Example function
 */
extern void lib_hello(void);

#endif /* SHARE_X_H */